// Phase 1B: LLM ラッパー

export {
  generateEmbedding,
  generateJSON,
  generateText,
  streamText,
  streamTextResult,
} from "./generate.js";
export {
  type AnalyzeSettingImpactContext,
  type AnalyzeStoryArcContext,
  analyzeSettingImpactPrompt,
  analyzeStoryArcPrompt,
  type CheckCharacterVoiceContext,
  type CreativeChatContext,
  chapterSummary,
  checkCharacterVoicePrompt,
  contentGeneration,
  createForeshadowingDraft,
  createSettingDraft,
  creativeChatSystemPrompt,
  editCharacter,
  editCharacterDocument,
  editCharacterSection,
  editForeshadowingDocument,
  editForeshadowingSection,
  editSetting,
  editSettingDocument,
  editSettingSection,
  editStoryOutlineDocument,
  editStoryOutlineSection,
  extractChatEntities,
  extractSettings,
  extractTimeline,
  type GenerateStyleGuideDraftContext,
  generatePlotFromStoryOutline,
  generateStyleGuideDraftPrompt,
  type InlineAssistAction,
  type InlineAssistContext,
  inlineAssistPrompt,
  type MultiPersonaReviewContext,
  multiPersonaReviewPrompt,
  type ProofreadContext,
  plotGeneration,
  proofreadPrompt,
  type ReaderPersonaType,
  sectionSummary,
} from "./prompts/index.js";
export {
  clearModelCache,
  createEmbeddingModel,
  createEmbeddingModelFromConfig,
  createEmbeddingProvider,
  createLanguageModel,
  createLanguageModelFromConfig,
  createLLMProvider,
  type EmbeddingConfigInput,
  type LLMConfigInput,
  type ProviderSettings,
  type TestConnectionResult,
  testEmbeddingConnection,
  testLLMConnection,
} from "./provider.js";
export {
  AVAILABLE_PROMPT_VARIABLES,
  renderPromptTemplate,
  type TemplateVariables,
} from "./templateEngine.js";
