// Phase 1B: LLM ラッパー
export {
  createLLMProvider,
  createEmbeddingProvider,
  createLanguageModel,
  createEmbeddingModel,
  createLanguageModelFromConfig,
  createEmbeddingModelFromConfig,
  testLLMConnection,
  testEmbeddingConnection,
  type LLMConfigInput,
  type EmbeddingConfigInput,
  type TestConnectionResult,
  type ProviderSettings,
} from './provider.js';

export {
  generateText,
  streamText,
  streamTextResult,
  generateJSON,
  generateEmbedding,
} from './generate.js';
export {
  plotGeneration,
  chapterSummary,
  sectionSummary,
  contentGeneration,
  extractTimeline,
  extractSettings,
  editCharacter,
  editSetting,
  createSettingDraft,
  editSettingSection,
  editCharacterSection,
  editSettingDocument,
  editCharacterDocument,
  editForeshadowingDocument,
  editForeshadowingSection,
  createForeshadowingDraft,
  creativeChatSystemPrompt,
  type CreativeChatContext,
  extractChatEntities,
  proofreadPrompt,
  type ProofreadContext,
  inlineAssistPrompt,
  type InlineAssistAction,
  type InlineAssistContext,
  checkCharacterVoicePrompt,
  type CheckCharacterVoiceContext,
  analyzeSettingImpactPrompt,
  type AnalyzeSettingImpactContext,
  analyzeStoryArcPrompt,
  type AnalyzeStoryArcContext,
  multiPersonaReviewPrompt,
  type ReaderPersonaType,
  type MultiPersonaReviewContext,
  generateStyleGuideDraftPrompt,
  type GenerateStyleGuideDraftContext,
} from './prompts/index.js';
