import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const promptsDir = path.resolve(__dirname, "../prompts");
const outDir = path.resolve(__dirname, "../src/prompts/generated");
const outFile = path.resolve(outDir, "templates.ts");

if (!fs.existsSync(promptsDir)) {
  fs.mkdirSync(promptsDir, { recursive: true });
}
if (!fs.existsSync(outDir)) {
  fs.mkdirSync(outDir, { recursive: true });
}

function parseFrontmatter(content) {
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!match) {
    return { metadata: {}, body: content };
  }

  const rawYaml = match[1];
  const body = match[2];
  const metadata = {};

  for (const line of rawYaml.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) {
      continue;
    }
    const colonIdx = trimmed.indexOf(":");
    if (colonIdx !== -1) {
      const key = trimmed.slice(0, colonIdx).trim();
      let val = trimmed.slice(colonIdx + 1).trim();
      if (
        (val.startsWith('"') && val.endsWith('"')) ||
        (val.startsWith("'") && val.endsWith("'"))
      ) {
        val = val.slice(1, -1);
      }
      metadata[key] = val;
    }
  }

  return { metadata, body };
}

const files = fs.readdirSync(promptsDir).filter((f) => f.endsWith(".md"));
const templates = {};

for (const file of files) {
  const name = path.basename(file, ".md");
  const fullPath = path.join(promptsDir, file);
  const content = fs.readFileSync(fullPath, "utf-8");
  const { metadata, body } = parseFrontmatter(content);
  templates[name] = {
    metadata: { name, ...metadata },
    body,
  };
}

const code = `// This file is auto-generated by scripts/build-prompts.mjs. Do not edit manually.
import type { PromptTemplate } from "../loader.js";

export const PROMPT_TEMPLATES: Record<string, PromptTemplate> = ${JSON.stringify(templates, null, 2)};
`;

fs.writeFileSync(outFile, code, "utf-8");
console.log(
  `Generated ${Object.keys(templates).length} prompt templates -> ${outFile}`
);
